// Generated by the Supabase MCP `generate_typescript_types` tool.
// Regenerate after schema migrations; do not edit by hand.

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[];

export type Database = {
	// Allows to automatically instantiate createClient with right options
	// instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
	__InternalSupabase: {
		PostgrestVersion: "14.5";
	};
	public: {
		Tables: {
			experience: {
				Row: {
					company: string;
					end_date: string;
					featured: boolean;
					highlights: string[];
					id: string;
					location: string | null;
					role: string;
					sort_order: number;
					start_date: string;
				};
				Insert: {
					company: string;
					end_date?: string;
					featured?: boolean;
					highlights?: string[];
					id?: string;
					location?: string | null;
					role: string;
					sort_order?: number;
					start_date: string;
				};
				Update: {
					company?: string;
					end_date?: string;
					featured?: boolean;
					highlights?: string[];
					id?: string;
					location?: string | null;
					role?: string;
					sort_order?: number;
					start_date?: string;
				};
				Relationships: [];
			};
			projects: {
				Row: {
					blurb: string;
					featured: boolean;
					href: string | null;
					id: string;
					image_url: string | null;
					role: string;
					sort_order: number;
					stack: string[];
					title: string;
					year: string;
				};
				Insert: {
					blurb?: string;
					featured?: boolean;
					href?: string | null;
					id?: string;
					image_url?: string | null;
					role?: string;
					sort_order?: number;
					stack?: string[];
					title: string;
					year?: string;
				};
				Update: {
					blurb?: string;
					featured?: boolean;
					href?: string | null;
					id?: string;
					image_url?: string | null;
					role?: string;
					sort_order?: number;
					stack?: string[];
					title?: string;
					year?: string;
				};
				Relationships: [];
			};
			site_settings: {
				Row: {
					id: number;
					resume_file_id: string;
					updated_at: string;
				};
				Insert: {
					id?: number;
					resume_file_id: string;
					updated_at?: string;
				};
				Update: {
					id?: number;
					resume_file_id?: string;
					updated_at?: string;
				};
				Relationships: [];
			};
			socials: {
				Row: {
					icon_svg: string;
					id: string;
					name: string;
					sort_order: number;
					url: string;
				};
				Insert: {
					icon_svg: string;
					id?: string;
					name: string;
					sort_order?: number;
					url: string;
				};
				Update: {
					icon_svg?: string;
					id?: string;
					name?: string;
					sort_order?: number;
					url?: string;
				};
				Relationships: [];
			};
			stats: {
				Row: {
					id: string;
					label: string;
					sort_order: number;
					suffix: string | null;
					value: number;
				};
				Insert: {
					id?: string;
					label: string;
					sort_order?: number;
					suffix?: string | null;
					value: number;
				};
				Update: {
					id?: string;
					label?: string;
					sort_order?: number;
					suffix?: string | null;
					value?: number;
				};
				Relationships: [];
			};
			tech_stacks: {
				Row: {
					category: string;
					id: string;
					skills: string[];
					sort_order: number;
				};
				Insert: {
					category: string;
					id?: string;
					skills?: string[];
					sort_order?: number;
				};
				Update: {
					category?: string;
					id?: string;
					skills?: string[];
					sort_order?: number;
				};
				Relationships: [];
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
	keyof Database,
	"public"
>];

export type Tables<
	DefaultSchemaTableNameOrOptions extends
		| keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
				DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
			DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
			Row: infer R;
		}
		? R
		: never
	: DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
				DefaultSchema["Views"])
		? (DefaultSchema["Tables"] &
				DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
				Row: infer R;
			}
			? R
			: never
		: never;

export type TablesInsert<
	DefaultSchemaTableNameOrOptions extends
		| keyof DefaultSchema["Tables"]
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
			Insert: infer I;
		}
		? I
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
		? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
				Insert: infer I;
			}
			? I
			: never
		: never;

export type TablesUpdate<
	DefaultSchemaTableNameOrOptions extends
		| keyof DefaultSchema["Tables"]
		| { schema: keyof DatabaseWithoutInternals },
	TableName extends DefaultSchemaTableNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
		: never = never,
> = DefaultSchemaTableNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
			Update: infer U;
		}
		? U
		: never
	: DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
		? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
				Update: infer U;
			}
			? U
			: never
		: never;

export type Enums<
	DefaultSchemaEnumNameOrOptions extends
		| keyof DefaultSchema["Enums"]
		| { schema: keyof DatabaseWithoutInternals },
	EnumName extends DefaultSchemaEnumNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
		: never = never,
> = DefaultSchemaEnumNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
	: DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
		? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
		: never;

export type CompositeTypes<
	PublicCompositeTypeNameOrOptions extends
		| keyof DefaultSchema["CompositeTypes"]
		| { schema: keyof DatabaseWithoutInternals },
	CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
		schema: keyof DatabaseWithoutInternals;
	}
		? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
		: never = never,
> = PublicCompositeTypeNameOrOptions extends {
	schema: keyof DatabaseWithoutInternals;
}
	? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
	: PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
		? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
		: never;

export const Constants = {
	public: {
		Enums: {},
	},
} as const;
